
spring:
  application:
    name: portfolio-demo
  jpa:
    hibernate:
      ddl-auto: create-drop
    datasource:
        url: jdbc:h2:file:~/portfolioDB
logging:
  level:
    root: INFO
    sql: DEBUG
    portfolio.portfoliodemo: DEBUG